import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:4000";
async function api(path:string,opt:any={}){const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(localStorage.tsx?{Authorization:"Bearer "+localStorage.tsx}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Error");return d}
const nav=[["planet","Planeta"],["research","Investigación"],["ships","Astillero"],["market","Mercado P2P"],["fleets","Flotas"],["alliance","Alianza"],["wallet","Wallet"],["ranking","Ranking"],["missions","Misiones"],["admin","Admin"]];
function Auth({on}:{on:()=>void}){const[reg,setReg]=useState(false),[u,setU]=useState(""),[p,setP]=useState(""),[e,setE]=useState("");async function go(){try{const d=await api(reg?"/auth/register":"/auth/login",{method:"POST",body:JSON.stringify({username:u,password:p})});localStorage.tsx=d.token;on()}catch(x:any){setE(x.message)}}return <div className="auth"><div className="panel"><div className="brand">⚡ TrendShopX <small>GAMEFI V2</small></div><h1>Tu imperio empieza aquí</h1><p>Planetas, investigación, flotas, batallas y mercado P2P.</p><input placeholder="Usuario" value={u} onChange={e=>setU(e.target.value)}/><input type="password" placeholder="Contraseña" value={p} onChange={e=>setP(e.target.value)}/><button onClick={go}>{reg?"Crear cuenta":"Entrar"}</button><button className="ghost" onClick={()=>setReg(!reg)}>{reg?"Ya tengo cuenta":"Crear una cuenta"}</button><b className="error">{e}</b></div></div>}
function App(){const[s,setS]=useState<any>(null),[page,setPage]=useState("planet"),[data,setData]=useState<any[]>([]),[msg,setMsg]=useState("");
 async function refresh(){try{setS(await api("/me"))}catch{localStorage.removeItem("tsx");setS(null)}}
 useEffect(()=>{if(localStorage.tsx)refresh()},[]);
 useEffect(()=>{setData([]);const m:any={research:"/research",ships:"/ships",market:"/market",fleets:"/fleets",alliance:"/alliances",ranking:"/ranking",missions:"/missions"};if(m[page])api(m[page]).then(setData).catch(e=>setMsg(e.message));},[page]);
 if(!s)return <Auth on={refresh}/>;
 const p=s.planets?.[0],w=s.wallet;const buildings=[["metalMine","⛏ Mina de Metal"],["crystalMine","💎 Mina de Cristal"],["deutSynth","🧪 Sintetizador"],["powerPlant","⚡ Planta de Energía"]];
 async function act(fn:()=>Promise<any>){try{await fn();setMsg("Acción completada");refresh()}catch(e:any){setMsg(e.message)}}
 return <div><header><div className="brand">⚡ TrendShopX <small>GAMEFI V2</small></div><nav>{nav.map(([k,n])=><button className={page===k?"active":""} onClick={()=>setPage(k)}>{n}</button>)}<button onClick={()=>{localStorage.removeItem("tsx");setS(null)}}>Salir</button></nav></header><main><div className="top"><div><span className="muted">COMANDANTE</span><h1>{s.user.username}</h1><p>{p?.name} · G{p?.galaxy}:S{p?.system}:P{p?.position}</p></div><div className="walletMini">TSX <b>{Math.floor(w.tsx)}</b> · USDT <b>{Number(w.usdt).toFixed(2)}</b></div></div>{msg&&<div className="notice">{msg}</div>}
 {page==="planet"&&<><div className="resources">{[["⛓️","Metal",p?.metal],["💎","Cristal",p?.crystal],["🧪","Deuterio",p?.deuterium],["⚡","Energía",p?.energy]].map(x=><div className="resource"><span>{x[0]} {x[1]}</span><b>{Math.floor(x[2]||0).toLocaleString()}</b></div>)}</div><div className="grid">{buildings.map(([k,n])=><div className="card"><h3>{n}</h3><div className="level">Nivel {p?.[k]}</div><p>Producción automática y economía planetaria.</p><button onClick={()=>act(()=>api("/build/upgrade",{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({type:k,planetId:p.id})}))}>Mejorar</button></div>)}</div></>}
 {page==="research"&&<><h2>Árbol tecnológico</h2><div className="grid">{data.map(r=><div className="card"><span className="tag">{r.type}</span><h3>Nivel {r.level}</h3><p>Mejora capacidades de combate, economía y exploración.</p><button onClick={()=>act(()=>api("/research/upgrade",{method:"POST",body:JSON.stringify({type:r.type,planetId:p.id})}))}>Investigar</button></div>)}</div></>}
 {page==="ships"&&<><h2>Astillero</h2><div className="grid">{["MINER","FIGHTER","CRUISER","TRANSPORT","EXPLORER"].map(t=><div className="card"><h3>{t}</h3><p>Unidades: {data.find(x=>x.type===t)?.quantity||0}</p><button onClick={()=>act(()=>api("/ships/build",{method:"POST",body:JSON.stringify({type:t,quantity:1,planetId:p.id})}))}>Construir 1</button></div>)}</div></>}
 {page==="market"&&<><h2>Mercado P2P · TSX/USDT</h2><p className="muted">Comisión: {s.marketFee}% · Solo TSX como activo negociable en V2.</p><div className="grid">{data.map(l=><div className="card"><span className="tag">TSX</span><h3>{l.quantity} TSX</h3><p>{l.price} USDT / TSX · {l.seller.username}</p><button onClick={()=>act(()=>api("/market/buy/"+l.id,{method:"POST"}))}>Comprar</button></div>)}</div></>}
 {page==="fleets"&&<><h2>Flotas</h2>{data.map(f=><div className="row"><b>{f.name}</b><span>{f.status} · ataque {f.attack} · defensa {f.defense}</span></div>)}<div className="card"><h3>Enviar expedición</h3><p>Selecciona otro planeta como destino cuando tengas una flota.</p><button onClick={()=>act(()=>api("/fleets/dispatch",{method:"POST",body:JSON.stringify({planetId:p.id,destinationPlanetId:p.id+1,minutes:5})}))}>Intentar enviar</button></div></>}
 {page==="alliance"&&<><h2>Alianzas</h2>{data.map(a=><div className="card"><span className="tag">{a.tag}</span><h3>{a.name}</h3><p>{a.members.length} miembros</p><button onClick={()=>act(()=>api("/alliances/"+a.id+"/join",{method:"POST"}))}>Unirme</button></div>)}</>}
 {page==="wallet"&&<><h2>Wallet</h2><div className="resources"><div className="resource"><span>TSX</span><b>{Number(w.tsx).toFixed(2)}</b></div><div className="resource"><span>USDT</span><b>{Number(w.usdt).toFixed(2)}</b></div></div><div className="grid"><div className="card"><h3>Depósito simulado</h3><button onClick={()=>act(()=>api("/web3/simulate/deposit",{method:"POST",body:JSON.stringify({asset:"USDT",amount:10})}))}>+10 USDT</button></div><div className="card"><h3>Retiro simulado</h3><button onClick={()=>act(()=>api("/web3/simulate/withdraw",{method:"POST",body:JSON.stringify({asset:"USDT",amount:1})}))}>-1 USDT</button></div></div></>}
 {page==="ranking"&&<><h2>Ranking</h2>{data.map((x,i)=><div className="row"><b>#{i+1} {x.user.username}</b><span>{Math.floor(x.metal+x.crystal+x.deuterium).toLocaleString()} recursos</span></div>)}</>}
 {page==="missions"&&<><h2>Misiones</h2>{data.map(m=><div className="card"><span className="tag">{m.users?.[0]?.status==="COMPLETED"?"COMPLETA":"ACTIVA"}</span><h3>{m.title}</h3><p>{m.description}</p><b>+{m.rewardTsx} TSX</b></div>)}<button onClick={()=>act(()=>api("/missions/check",{method:"POST"}))}>Comprobar misiones</button></>}
 {page==="admin"&&<Admin/>}
 </main></div>}
function Admin(){const[d,setD]=useState<any>(null);useEffect(()=>{api("/admin/stats").then(setD).catch(()=>setD({error:"Solo administradores"}))},[]);return <><h2>Panel administrativo</h2>{d?.error?<div className="card">{d.error}</div>:<div className="grid">{Object.entries(d||{}).map(([k,v])=><div className="resource"><span>{k}</span><b>{String(v)}</b></div>)}</div>}</>}
createRoot(document.getElementById("root")!).render(<App/>);
