import React,{useEffect,useState} from "react";import{createRoot}from"react-dom/client";import"./styles.css";
const API=import.meta.env.VITE_API_URL||"http://localhost:4000";const api=async(path:string,opt:any={})=>{const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(localStorage.tsx?{Authorization:"Bearer "+localStorage.tsx}: {})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Error");return d};
type State={user:any,planet:any,wallet:any,marketFee:number};
function Auth({on}:{on:()=>void}){const[reg,setReg]=useState(false),[u,setU]=useState(""),[p,setP]=useState(""),[e,setE]=useState("");async function go(){try{const d=await api(reg?"/auth/register":"/auth/login",{method:"POST",body:JSON.stringify({username:u,password:p})});localStorage.tsx=d.token;on()}catch(x:any){setE(x.message)}}return <div className="auth"><div className="panel"><div className="brand">⚡ TrendShopX <small>GAMEFI</small></div><h1>Construye tu imperio espacial</h1><p>Produce recursos, crea flotas y comercia en el mercado P2P.</p><input placeholder="Usuario" value={u} onChange={e=>setU(e.target.value)}/><input type="password" placeholder="Contraseña" value={p} onChange={e=>setP(e.target.value)}/><button onClick={go}>{reg?"Crear cuenta":"Entrar"}</button><button className="ghost" onClick={()=>setReg(!reg)}>{reg?"Ya tengo cuenta":"Crear una cuenta"}</button><b className="error">{e}</b></div></div>}
function App(){const[s,setS]=useState<State|null>(null),[page,setPage]=useState("planet"),[market,setMarket]=useState<any[]>([]),[rank,setRank]=useState<any[]>([]),[ledger,setLedger]=useState<any[]>([]),[missions,setMissions]=useState<any[]>([]);
 async function refresh(){try{setS(await api("/me"))}catch{localStorage.removeItem("tsx");setS(null)}}useEffect(()=>{if(localStorage.tsx)refresh()},[]);
 useEffect(()=>{if(page==="market")api("/market").then(setMarket);if(page==="ranking")api("/ranking").then(setRank);if(page==="wallet")api("/wallet/ledger").then(setLedger);if(page==="missions")api("/missions").then(setMissions)},[page]);
 if(!s)return <Auth on={refresh}/>;
 const p=s.planet,w=s.wallet;const buildings=[["metalMine","⛏️ Mina de Metal"],["crystalMine","💎 Mina de Cristal"],["deutSynth","🧪 Sintetizador"],["powerPlant","⚡ Planta"]];
 async function upgrade(type:string){try{await api("/build/upgrade",{method:"POST",body:JSON.stringify({type})});refresh()}catch(e:any){alert(e.message)}}
 return <div><header><div className="brand">⚡ TrendShopX <small>GAMEFI</small></div><nav>{["planet","market","wallet","ranking","missions"].map(x=><button className={page===x?"active":""} onClick={()=>setPage(x)}>{x==="planet"?"Planeta":x==="market"?"Mercado":x==="wallet"?"Wallet":x==="ranking"?"Ranking":"Misiones"}</button>)}<button onClick={()=>{localStorage.removeItem("tsx");setS(null)}}>Salir</button></nav></header><main>
 <section className="top"><div><span className="muted">COMANDANTE</span><h1>{s.user.username}</h1><p>Tu colonia está produciendo recursos automáticamente.</p></div><div className="walletMini">TSX <b>{Math.floor(w.tsx)}</b><br/>USDT <b>{w.usdt.toFixed(2)}</b></div></section>
 {page==="planet"&&<><div className="resources">{[["⛓️","Metal",p.metal],["💎","Cristal",p.crystal],["🧪","Deuterio",p.deuterium],["⚡","Energía",p.energy]].map(x=><div className="resource"><span>{x[0]} {x[1]}</span><b>{Math.floor(x[2]).toLocaleString()}</b></div>)}</div><h2>{p.name}</h2><div className="grid">{buildings.map(([k,n])=><div className="card"><h3>{n}</h3><div className="level">Nivel {p[k]}</div><p>Mejora tu producción y capacidad.</p><button onClick={()=>upgrade(k)}>Mejorar</button></div>)}</div></>}
 {page==="market"&&<><h2>Mercado P2P</h2><p className="muted">Comisión actual: {s.marketFee}%</p><div className="grid">{market.map(l=><div className="card"><span className="tag">{l.asset}</span><h3>{l.quantity} {l.asset}</h3><p>{l.price} USDT / unidad · vendedor {l.seller.username}</p><button onClick={async()=>{try{await api("/market/buy/"+l.id,{method:"POST"});setMarket(await api("/market"))}catch(e:any){alert(e.message)}}}>Comprar</button></div>)}</div></>}
 {page==="wallet"&&<><h2>Wallet</h2><div className="resources"><div className="resource"><span>TSX</span><b>{w.tsx.toFixed(2)}</b></div><div className="resource"><span>USDT</span><b>{w.usdt.toFixed(2)}</b></div></div><h2>Ledger</h2>{ledger.map(x=><div className="row"><span>{x.type} · {x.asset}</span><b>{x.amount>0?"+":""}{x.amount}</b></div>)}</>}
 {page==="ranking"&&<><h2>Ranking</h2>{rank.map((x,i)=><div className="row"><b>#{i+1} {x.user.username}</b><span>{Math.floor(x.metal+x.crystal+x.deuterium).toLocaleString()} recursos</span></div>)}</>}
 {page==="missions"&&<><h2>Misiones</h2>{missions.map(m=><div className="card"><span className="tag">{m.users.length?"COMPLETA":"ACTIVA"}</span><h3>{m.title}</h3><p>{m.description}</p><b>+{m.rewardTsx} TSX</b></div>)}</>}
 </main></div>}
createRoot(document.getElementById("root")!).render(<App/>);