import express from "express";
import cors from "cors";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import dotenv from "dotenv";
import rateLimit from "express-rate-limit";
import { PrismaClient, Asset, LedgerType, ListingStatus, Role, FleetStatus, FleetMission, ResearchType, ShipType, DefenseType, NotificationType, BlockchainProvider, JobType, OrderSide, OrderStatus, ReferralStatus } from "@prisma/client";
import { createServer } from "node:http";
import { WebSocketServer } from "ws";
dotenv.config();

const prisma=new PrismaClient(), app=express(), http=createServer(app);
const wss=new WebSocketServer({server:http,path:"/ws"});
const PORT=Number(process.env.API_PORT||4000), SECRET=process.env.JWT_SECRET||"dev-secret";
const FEE=Number(process.env.MARKET_FEE_PERCENT||3), ORIGIN=process.env.WEB_ORIGIN?.split(",")||true;
app.use(cors({origin:ORIGIN})); app.use(express.json({limit:"200kb"}));
app.use(rateLimit({windowMs:60000,max:Number(process.env.RATE_LIMIT||120),standardHeaders:true,legacyHeaders:false}));
type Token={id:number,username:string,role:Role};
const auth=(req:any,res:any,next:any)=>{const h=req.headers.authorization||"";if(!h.startsWith("Bearer "))return res.status(401).json({error:"No autenticado"});try{req.user=jwt.verify(h.slice(7),SECRET) as Token;next()}catch{return res.status(401).json({error:"Token inválido"})}};
const sign=(u:Token)=>jwt.sign(u,SECRET,{expiresIn:"7d"});
const num=(v:any,min=0)=>{const n=Number(v);return Number.isFinite(n)&&n>=min?n:null};
const buildingTypes=["metalMine","crystalMine","deutSynth","powerPlant","hangarLevel","defenseLevel"];
const shipStats:any={MINER:{attack:4,defense:12,speed:80},FIGHTER:{attack:20,defense:10,speed:180},CRUISER:{attack:45,defense:30,speed:140},TRANSPORT:{attack:2,defense:18,speed:100},EXPLORER:{attack:12,defense:15,speed:220}};
const shipCost:any={MINER:{metal:500,crystal:250,deuterium:0},FIGHTER:{metal:1000,crystal:500,deuterium:100},CRUISER:{metal:3000,crystal:1500,deuterium:500},TRANSPORT:{metal:2000,crystal:1000,deuterium:100},EXPLORER:{metal:1500,crystal:1200,deuterium:400}};
const defenseStats:any={CANNON:{attack:25,defense:45,cost:{metal:500,crystal:100,deuterium:0}},LASER:{attack:40,defense:25,cost:{metal:700,crystal:300,deuterium:0}},PLASMA:{attack:120,defense:100,cost:{metal:5000,crystal:3000,deuterium:500}},SHIELD:{attack:5,defense:500,cost:{metal:1000,crystal:1000,deuterium:200}}};

async function tickPlanet(id:number){const p=await prisma.planet.findUnique({where:{id}});if(!p)return null;const now=new Date(),ms=Math.max(0,Math.min(now.getTime()-p.lastTick.getTime(),86400000)),h=ms/3600000;if(ms<1000)return p;return prisma.planet.update({where:{id},data:{metal:{increment:30*p.metalMine*Math.pow(1.15,p.metalMine-1)*h},crystal:{increment:20*p.crystalMine*Math.pow(1.15,p.crystalMine-1)*h},deuterium:{increment:8*p.deutSynth*Math.pow(1.15,p.deutSynth-1)*h},lastTick:now}})}
async function tickUser(id:number){return Promise.all((await prisma.planet.findMany({where:{userId:id}})).map(p=>tickPlanet(p.id)))}
async function freePosition(tx:any){const used=await tx.planet.findMany({where:{galaxy:1,system:1},select:{position:true}});const s=new Set(used.map((x:any)=>x.position));for(let i=1;i<=15;i++)if(!s.has(i))return i;return Math.floor(Math.random()*900)+100}
async function notify(userId:number,type:NotificationType,title:string,message:string){const n=await prisma.notification.create({data:{userId,type,title,message}});const p=JSON.stringify({type:"notification",data:n});wss.clients.forEach(c=>{if(c.readyState===1)c.send(p)});return n}
async function audit(userId:number|undefined,action:string,entity:string,entityId?:string,metadata?:any){return prisma.auditLog.create({data:{userId,action,entity,entityId,metadata}})}
async function idem(req:any,res:any,next:any){const key=String(req.headers["idempotency-key"]||"");if(!key)return next();const u=req.user as Token;const old=await prisma.idempotencyKey.findUnique({where:{userId_key:{userId:u.id,key}}});if(old)return res.json(old.response);req.idempotencyKey=key;next()}
async function completeJobs(userId:number){const jobs=await prisma.buildJob.findMany({where:{userId,status:"QUEUED",finishAt:{lte:new Date()}},orderBy:{id:"asc"}});for(const j of jobs){if(j.type===JobType.BUILDING&&buildingTypes.includes(j.target)){await prisma.planet.update({where:{id:j.planetId},data:{[j.target]:{increment:1}}})}else if(j.type===JobType.RESEARCH){const r=await prisma.research.findFirst({where:{userId,planetId:j.planetId,type:j.target as ResearchType}});if(r)await prisma.research.update({where:{id:r.id},data:{level:j.targetLevel}})}else if(j.type===JobType.SHIP){await prisma.ship.upsert({where:{userId_type:{userId,type:j.target as ShipType}},update:{quantity:{increment:j.quantity}},create:{userId,type:j.target as ShipType,quantity:j.quantity}})}await prisma.buildJob.update({where:{id:j.id},data:{status:"DONE"}});await notify(userId,NotificationType.SYSTEM,"Cola completada",j.target+" terminó su producción.")}}
async function completeExpeditions(userId:number){const ex=await prisma.expedition.findMany({where:{userId,status:"RUNNING",finishAt:{lte:new Date()}}});for(const e of ex){const roll=Math.random(),event=roll<.12?"ANOMALY":roll<.22?"PIRATES":"RESOURCE_RICH";const mult=event==="PIRATES"?.45:event==="ANOMALY"?1.8:1;const reward={tsx:Math.floor((40+Math.random()*160)*mult),metal:Math.floor((700+Math.random()*3300)*mult),crystal:Math.floor((300+Math.random()*1800)*mult)};const p=await prisma.planet.findFirst({where:{userId}});if(p)await prisma.planet.update({where:{id:p.id},data:{metal:{increment:reward.metal},crystal:{increment:reward.crystal}}});await prisma.wallet.update({where:{userId},data:{tsx:{increment:reward.tsx}}});await prisma.ledger.create({data:{userId,asset:Asset.TSX,amount:reward.tsx,type:LedgerType.REWARD,reference:"expedition:"+e.id}});await prisma.expedition.update({where:{id:e.id},data:{status:"COMPLETED",event,rewardTsx:reward.tsx,rewardMetal:reward.metal,rewardCrystal:reward.crystal}});if(e.fleetId)await prisma.fleet.update({where:{id:e.fleetId},data:{status:FleetStatus.IDLE,mission:FleetMission.TRANSPORT}});await notify(userId,NotificationType.MISSION,"Expedición completada",event+" · +"+reward.tsx+" TSX")}}

app.get("/health",(_,res)=>res.json({ok:true,service:"trendshopx-gamefi-api",version:"4.0.0",time:new Date().toISOString()}));
app.post("/auth/register",async(req,res)=>{const username=String(req.body.username||"").trim().toLowerCase(),password=String(req.body.password||""),ref=String(req.body.referralCode||"");if(!/^[a-z0-9_]{3,20}$/.test(username)||password.length<6)return res.status(400).json({error:"Usuario 3-20 y contraseña mínima de 6."});try{const result=await prisma.$transaction(async tx=>{const position=await freePosition(tx);const u=await tx.user.create({data:{username,passwordHash:await bcrypt.hash(password,12)}});const p=await tx.planet.create({data:{userId:u.id,name:username+"'s World",galaxy:1,system:1,position}});await tx.wallet.create({data:{userId:u.id,tsx:1000}});await tx.ledger.create({data:{userId:u.id,asset:Asset.TSX,amount:1000,type:LedgerType.BONUS,reference:"welcome"}});for(const type of Object.values(ResearchType))await tx.research.create({data:{userId:u.id,planetId:p.id,type,level:1}});if(ref){const parent=await tx.user.findUnique({where:{referralCode:ref}});if(parent&&parent.id!==u.id)await tx.referral.create({data:{referrerId:parent.id,referredId:u.id,rewardTsx:100}})}return {id:u.id,username:u.username,role:u.role}});res.json({token:sign(result as Token),user:result})}catch{res.status(409).json({error:"No se pudo crear la cuenta; prueba otro usuario."})}});
app.post("/auth/login",async(req,res)=>{const u=await prisma.user.findUnique({where:{username:String(req.body.username||"").trim().toLowerCase()}});if(!u||!(await bcrypt.compare(String(req.body.password||""),u.passwordHash)))return res.status(401).json({error:"Credenciales incorrectas"});res.json({token:sign({id:u.id,username:u.username,role:u.role}),user:{id:u.id,username:u.username,role:u.role}})});
app.get("/me",auth,async(req,res)=>{const u=req.user as Token;await completeJobs(u.id);await completeExpeditions(u.id);const ps=await tickUser(u.id),w=await prisma.wallet.findUnique({where:{userId:u.id}}),ships=await prisma.ship.findMany({where:{userId:u.id}}),defs=await prisma.defense.findMany({where:{planetId:ps[0]?.id}});res.json({user:u,planets:ps,wallet:w,ships,defenses:defs,marketFee:FEE,version:"4.0.0"})});
app.get("/planets",auth,async(req,res)=>res.json(await tickUser((req.user as Token).id)));
app.post("/planets",auth,async(req,res)=>{const u=req.user as Token;const p=await prisma.planet.create({data:{userId:u.id,name:String(req.body.name||"Colonia"),galaxy:1,system:1,position:await freePosition(prisma)}});res.json(p)});
app.post("/build/upgrade",auth,idem,async(req,res)=>{const u=req.user as Token,type=String(req.body.type||""),planetId=Number(req.body.planetId);if(!buildingTypes.includes(type))return res.status(400).json({error:"Edificio inválido"});const p=await prisma.planet.findFirst({where:{id:planetId,userId:u.id}});if(!p)return res.status(404).json({error:"Planeta no encontrado"});await tickPlanet(p.id);const f=await prisma.planet.findUnique({where:{id:p.id}}) as any;const base:any={metalMine:[120,70,0],crystalMine:[180,110,0],deutSynth:[225,160,20],powerPlant:[90,70,0],hangarLevel:[800,500,200],defenseLevel:[600,400,100]}[type];const level=f[type],k=Math.pow(1.55,Math.max(0,level-1)),c={metal:Math.ceil(base[0]*k),crystal:Math.ceil(base[1]*k),deuterium:Math.ceil(base[2]*k)};if(f.metal<c.metal||f.crystal<c.crystal||f.deuterium<c.deuterium)return res.status(400).json({error:"Recursos insuficientes",cost:c});const out=await prisma.$transaction(async tx=>{await tx.planet.update({where:{id:p.id},data:{metal:{decrement:c.metal},crystal:{decrement:c.crystal},deuterium:{decrement:c.deuterium}}});return tx.buildJob.create({data:{userId:u.id,planetId:p.id,type:JobType.BUILDING,target,typeLevel:undefined as any,targetLevel:level+1,finishAt:new Date(Date.now()+Math.max(1,level)*60000)}})}).catch(()=>null);if(!out)return res.status(500).json({error:"No se pudo crear la cola"});res.json(out)});
app.get("/jobs",auth,async(req,res)=>{const u=req.user as Token;await completeJobs(u.id);res.json(await prisma.buildJob.findMany({where:{userId:u.id},orderBy:{id:"desc"},take:100}) )});
app.post("/jobs/research",auth,idem,async(req,res)=>{const u=req.user as Token,type=String(req.body.type||"") as ResearchType,pid=Number(req.body.planetId);if(!Object.values(ResearchType).includes(type))return res.status(400).json({error:"Investigación inválida"});const r=await prisma.research.findUnique({where:{userId_type:{userId:u.id,type}}}),p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}});if(!r||!p)return res.status(404).json({error:"Datos no encontrados"});await tickPlanet(pid);const f=await prisma.planet.findUnique({where:{id:pid}}) as any,c={metal:Math.ceil(800*Math.pow(1.8,r.level-1)),crystal:Math.ceil(500*Math.pow(1.7,r.level-1)),deuterium:Math.ceil(200*Math.pow(1.6,r.level-1))};if(f.metal<c.metal||f.crystal<c.crystal||f.deuterium<c.deuterium)return res.status(400).json({error:"Recursos insuficientes",cost:c});await prisma.planet.update({where:{id:pid},data:{metal:{decrement:c.metal},crystal:{decrement:c.crystal},deuterium:{decrement:c.deuterium}}});res.json(await prisma.buildJob.create({data:{userId:u.id,planetId:pid,type:JobType.RESEARCH,target:type,targetLevel:r.level+1,finishAt:new Date(Date.now()+Math.max(2,r.level)*120000)}}))});
app.get("/research",auth,async(req,res)=>res.json(await prisma.research.findMany({where:{userId:(req.user as Token).id}})));
app.get("/ships",auth,async(req,res)=>res.json(await prisma.ship.findMany({where:{userId:(req.user as Token).id}})));
app.post("/ships/build",auth,idem,async(req,res)=>{const u=req.user as Token,t=String(req.body.type||"") as ShipType,q=num(req.body.quantity,1),pid=Number(req.body.planetId);if(!q||!Object.values(ShipType).includes(t))return res.status(400).json({error:"Nave/cantidad inválida"});const p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}});if(!p)return res.status(404).json({error:"Planeta no encontrado"});const c=shipCost[t],f=await prisma.planet.findUnique({where:{id:pid}}) as any,total={metal:c.metal*q,crystal:c.crystal*q,deuterium:c.deuterium*q};if(f.metal<total.metal||f.crystal<total.crystal||f.deuterium<total.deuterium)return res.status(400).json({error:"Recursos insuficientes",cost:total});await prisma.planet.update({where:{id:pid},data:{metal:{decrement:total.metal},crystal:{decrement:total.crystal},deuterium:{decrement:total.deuterium}}});res.json(await prisma.buildJob.create({data:{userId:u.id,planetId:pid,type:JobType.SHIP,target:t,targetLevel:1,quantity:q,finishAt:new Date(Date.now()+Math.max(1,Math.ceil(q/2))*60000)}}))});
app.get("/defenses",auth,async(req,res)=>{const u=req.user as Token,p=await prisma.planet.findFirst({where:{id:Number(req.query.planetId),userId:u.id}});if(!p)return res.status(404).json({error:"Planeta no encontrado"});res.json(await prisma.defense.findMany({where:{planetId:p.id}}))});
app.post("/defenses/build",auth,idem,async(req,res)=>{const u=req.user as Token,t=String(req.body.type||"") as DefenseType,q=num(req.body.quantity,1),pid=Number(req.body.planetId);if(!q||!Object.values(DefenseType).includes(t))return res.status(400).json({error:"Defensa/cantidad inválida"});const p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}}),s=defenseStats[t];if(!p)return res.status(404).json({error:"Planeta no encontrado"});const f=await prisma.planet.findUnique({where:{id:pid}}) as any,total={metal:s.cost.metal*q,crystal:s.cost.crystal*q,deuterium:s.cost.deuterium*q};if(f.metal<total.metal||f.crystal<total.crystal||f.deuterium<total.deuterium)return res.status(400).json({error:"Recursos insuficientes",cost:total});await prisma.planet.update({where:{id:pid},data:{metal:{decrement:total.metal},crystal:{decrement:total.crystal},deuterium:{decrement:total.deuterium}}});res.json(await prisma.defense.upsert({where:{planetId_type:{planetId:pid,type:t}},update:{quantity:{increment:q}},create:{planetId:pid,type:t,quantity:q,attack:s.attack,defense:s.defense}}))});
app.get("/fleets",auth,async(req,res)=>res.json(await prisma.fleet.findMany({where:{userId:(req.user as Token).id},include:{origin:true,destination:true}})));
app.post("/fleets",auth,async(req,res)=>{const u=req.user as Token,pid=Number(req.body.planetId),ships=req.body.ships||{};const p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}});if(!p)return res.status(404).json({error:"Planeta no encontrado"});res.json(await prisma.fleet.create({data:{userId:u.id,planetId:pid,name:String(req.body.name||"Fleet "+Date.now()),ships,attack:10,defense:10,speed:100}}))});
app.post("/fleets/dispatch",auth,idem,async(req,res)=>{const u=req.user as Token,fid=Number(req.body.fleetId),dest=Number(req.body.destinationPlanetId),mission=String(req.body.mission||"TRANSPORT") as FleetMission,mins=Math.max(1,Math.min(1440,Math.floor(Number(req.body.minutes)||5)));const f=await prisma.fleet.findFirst({where:{id:fid,userId:u.id,status:FleetStatus.IDLE}}),d=await prisma.planet.findUnique({where:{id:dest}});if(!f||!d||d.id===f.planetId)return res.status(400).json({error:"Flota/destino inválido"});const now=new Date(),arrival=new Date(now.getTime()+mins*60000);res.json(await prisma.fleet.update({where:{id:f.id},data:{status:FleetStatus.TRAVELING,mission,destinationPlanetId:dest,departureAt:now,arrivalAt:arrival,cargo:req.body.cargo||{}}}))});
app.post("/fleets/arrive",auth,async(req,res)=>{const u=req.user as Token,f=await prisma.fleet.findFirst({where:{id:Number(req.body.fleetId),userId:u.id,status:FleetStatus.TRAVELING}});if(!f)return res.status(404).json({error:"Flota no encontrada"});if(!f.arrivalAt||f.arrivalAt>new Date())return res.status(400).json({error:"La flota aún está en viaje",arrivalAt:f.arrivalAt});res.json(await prisma.fleet.update({where:{id:f.id},data:{status:FleetStatus.RETURNING}}))});
app.get("/battle/:defenderId",auth,async(req,res)=>{const a=req.user as Token,did=Number(req.params.defenderId);if(did===a.id)return res.status(400).json({error:"No puedes atacarte"});const def=await prisma.user.findUnique({where:{id:did},include:{planets:true,ships:true,defenses:{include:{planet:true}}}),att=await prisma.user.findUnique({where:{id:a.id},include:{ships:true}});if(!def||!att)return res.status(404).json({error:"Jugador no encontrado"});const ap=att.ships.reduce((s,x)=>s+x.quantity*(shipStats[x.type]?.attack||0),0),dp=def.ships.reduce((s,x)=>s+x.quantity*(shipStats[x.type]?.attack||0),0)+def.defenses.reduce((s,x)=>s+x.quantity*x.attack,0),winner=ap>=dp?a.id:did;const lossA=att.ships.map(x=>({type:x.type,lost:Math.min(x.quantity,Math.floor(x.quantity*(0.05+(dp/(ap+dp+1))*0.35)))})),lossD=def.ships.map(x=>({type:x.type,lost:Math.min(x.quantity,Math.floor(x.quantity*(0.05+(ap/(ap+dp+1))*0.35)))}));for(const x of lossA)if(x.lost)await prisma.ship.update({where:{userId_type:{userId:a.id,type:x.type}},data:{quantity:{decrement:x.lost}}});for(const x of lossD)if(x.lost)await prisma.ship.update({where:{userId_type:{userId:did,type:x.type}},data:{quantity:{decrement:x.lost}}});const report=await prisma.battleReport.create({data:{attackerId:a.id,defenderId:did,winnerId:winner,attackerPower:ap,defenderPower:dp,attackerLosses:lossA,defenderLosses:lossD,loot:{metal:winner===a.id?Math.floor((def.planets[0]?.metal||0)*0.1):0}}});await prisma.seasonScore.upsert({where:{seasonId_userId:{seasonId:(await activeSeason())?.id||0,userId:winner}},update:{points:{increment:25}},create:{seasonId:(await activeSeason())?.id||0,userId:winner,points:25}}).catch(()=>{});res.json(report)});
async function activeSeason(){const now=new Date();return prisma.season.findFirst({where:{startsAt:{lte:now},endsAt:{gte:now}},orderBy:{startsAt:"desc"}})}
app.get("/ranking",auth,async(_,res)=>{const rows=await prisma.planet.groupBy({by:["userId"],_sum:{metal:true,crystal:true,deuterium:true},orderBy:{_sum:{metal:"desc"}},take:50});const users=await prisma.user.findMany({where:{id:{in:rows.map(r=>r.userId)}},select:{id:true,username:true}});res.json(rows.map(r=>({user:users.find(u=>u.id===r.userId),metal:r._sum.metal||0,crystal:r._sum.crystal||0,deuterium:r._sum.deuterium||0})))});
app.get("/market",auth,async(_,res)=>res.json(await prisma.marketOrder.findMany({where:{status:OrderStatus.OPEN},include:{user:{select:{username:true}}},orderBy:{price:"asc"},take:100})));
app.post("/market/orders",auth,idem,async(req,res)=>{const u=req.user as Token,side=String(req.body.side||"SELL") as OrderSide,q=num(req.body.quantity,0.0001),price=num(req.body.price,0.0000001);if(!q||!price||!Object.values(OrderSide).includes(side))return res.status(400).json({error:"Orden inválida"});const w=await prisma.wallet.findUnique({where:{userId:u.id}});if(!w)return res.status(404).json({error:"Wallet"});if(side===OrderSide.SELL&&w.tsx<q)return res.status(400).json({error:"TSX insuficiente"});if(side===OrderSide.BUY&&w.usdt<q*price*(1+FEE/100))return res.status(400).json({error:"USDT insuficiente"});if(side===OrderSide.SELL)await prisma.wallet.update({where:{userId:u.id},data:{tsx:{decrement:q},lockedTsx:{increment:q}}});else await prisma.wallet.update({where:{userId:u.id},data:{usdt:{decrement:q*price*(1+FEE/100)},lockedUsdt:{increment:q*price*(1+FEE/100)}}});res.json(await prisma.marketOrder.create({data:{userId:u.id,side,quantity:q,remaining:q,price}}))});
app.post("/market/orders/:id/cancel",auth,async(req,res)=>{const u=req.user as Token,o=await prisma.marketOrder.findFirst({where:{id:Number(req.params.id),userId:u.id,status:OrderStatus.OPEN}});if(!o)return res.status(404).json({error:"Orden no encontrada"});if(o.side===OrderSide.SELL)await prisma.wallet.update({where:{userId:u.id},data:{tsx:{increment:o.remaining},lockedTsx:{decrement:o.remaining}}});else await prisma.wallet.update({where:{userId:u.id},data:{usdt:{increment:o.remaining*o.price*(1+FEE/100)},lockedUsdt:{decrement:o.remaining*o.price*(1+FEE/100)}}});res.json(await prisma.marketOrder.update({where:{id:o.id},data:{status:OrderStatus.CANCELLED}}))});
app.post("/market/orders/:id/fill",auth,idem,async(req,res)=>{const u=req.user as Token,buy=await prisma.marketOrder.findFirst({where:{id:Number(req.params.id),status:OrderStatus.OPEN}});const q=num(req.body.quantity,0.0001);if(!buy||!q||q>buy.remaining||buy.userId===u.id||buy.side!==OrderSide.SELL)return res.status(400).json({error:"Orden inválida"});const total=q*buy.price,fee=total*FEE/100,bw=await prisma.wallet.findUnique({where:{userId:u.id}});if(!bw||bw.usdt<total+fee)return res.status(400).json({error:"USDT insuficiente"});await prisma.$transaction(async tx=>{await tx.wallet.update({where:{userId:u.id},data:{usdt:{decrement:total+fee}}});await tx.wallet.update({where:{userId:buy.userId},data:{lockedTsx:{decrement:q},usdt:{increment:total}}});await tx.wallet.update({where:{userId:u.id},data:{tsx:{increment:q}}});await tx.marketOrder.update({where:{id:buy.id},data:{remaining:{decrement:q},status:q===buy.remaining?OrderStatus.FILLED:OrderStatus.PARTIAL}});await tx.ledger.createMany({data:[{userId:u.id,asset:Asset.USDT,amount:-total-fee,type:LedgerType.MARKET_BUY},{userId:buy.userId,asset:Asset.TSX,amount:-q,type:LedgerType.MARKET_SELL},{userId:buy.userId,asset:Asset.USDT,amount:total,type:LedgerType.MARKET_SELL},{userId:u.id,asset:Asset.TSX,amount:q,type:LedgerType.MARKET_BUY},{userId:u.id,asset:Asset.USDT,amount:-fee,type:LedgerType.MARKET_FEE}]})});res.json({filled:q,total,fee})});
app.get("/wallet/ledger",auth,async(req,res)=>res.json(await prisma.ledger.findMany({where:{userId:(req.user as Token).id},orderBy:{id:"desc"},take:100})));
app.post("/web3/simulate/deposit",auth,async(req,res)=>{const u=req.user as Token,a=String(req.body.asset||"USDT") as Asset,amount=num(req.body.amount,0.0001);if(!amount||!Object.values(Asset).includes(a))return res.status(400).json({error:"Depósito inválido"});const hash="sim_"+Date.now()+"_"+Math.random().toString(36).slice(2);const f=a.toLowerCase();await prisma.wallet.update({where:{userId:u.id},data:{[f]:{increment:amount}}});res.json({mode:"SIMULATED",txHash:hash,asset:a,amount})});
app.post("/web3/simulate/withdraw",auth,async(req,res)=>{const u=req.user as Token,a=String(req.body.asset||"USDT") as Asset,amount=num(req.body.amount,0.0001);if(!amount||!Object.values(Asset).includes(a))return res.status(400).json({error:"Retiro inválido"});const f=a.toLowerCase(),w=await prisma.wallet.findUnique({where:{userId:u.id}}) as any;if(w[f]<amount)return res.status(400).json({error:"Saldo insuficiente"});const hash="sim_"+Date.now()+"_"+Math.random().toString(36).slice(2);await prisma.wallet.update({where:{userId:u.id},data:{[f]:{decrement:amount}}});res.json({mode:"SIMULATED",txHash:hash,asset:a,amount})});
app.get("/expeditions",auth,async(req,res)=>{const u=req.user as Token;await completeExpeditions(u.id);res.json(await prisma.expedition.findMany({where:{userId:u.id},orderBy:{id:"desc"},take:50}))});
app.post("/expeditions/start",auth,idem,async(req,res)=>{const u=req.user as Token,minutes=Math.max(2,Math.min(180,Math.floor(Number(req.body.minutes)||10))),f=await prisma.fleet.findFirst({where:{userId:u.id,status:FleetStatus.IDLE}});if(!f)return res.status(400).json({error:"Necesitas una flota IDLE"});await prisma.fleet.update({where:{id:f.id},data:{status:FleetStatus.TRAVELING,mission:FleetMission.EXPEDITION}});res.json(await prisma.expedition.create({data:{userId:u.id,fleetId:f.id,finishAt:new Date(Date.now()+minutes*60000)}}))});
app.get("/seasons",async(_,res)=>res.json(await prisma.season.findMany({include:{scores:{include:{user:{select:{username:true}}},orderBy:{points:"desc"},take:100}},orderBy:{startsAt:"desc"}})));
app.post("/admin/seasons",auth,async(req,res)=>{const u=req.user as Token;if(![Role.ADMIN,Role.SUPER_ADMIN].includes(u.role))return res.status(403).json({error:"Solo admin"});const starts=new Date(req.body.startsAt),ends=new Date(req.body.endsAt);if(isNaN(starts.getTime())||isNaN(ends.getTime())||ends<=starts)return res.status(400).json({error:"Fechas inválidas"});res.json(await prisma.season.create({data:{name:String(req.body.name||"Temporada"),startsAt:starts,endsAt:ends}}))});
app.get("/referrals",auth,async(req,res)=>{const u=req.user as Token;res.json({code:(await prisma.user.findUnique({where:{id:u.id},select:{referralCode:true}}))?.referralCode,items:await prisma.referral.findMany({where:{OR:[{referrerId:u.id},{referredId:u.id}]},include:{referred:{select:{username:true}},referrer:{select:{username:true}}}})})});
app.post("/referrals/activate",auth,async(req,res)=>{const u=req.user as Token,r=await prisma.referral.findUnique({where:{referredId:u.id}});if(!r||r.status!==ReferralStatus.PENDING)return res.status(400).json({error:"No hay referido pendiente"});await prisma.$transaction(async tx=>{await tx.referral.update({where:{id:r.id},data:{status:ReferralStatus.REWARDED,rewardedAt:new Date()}});await tx.wallet.update({where:{userId:r.referrerId},data:{tsx:{increment:r.rewardTsx}}});await tx.ledger.create({data:{userId:r.referrerId,asset:Asset.TSX,amount:r.rewardTsx,type:LedgerType.REWARD,reference:"referral:"+r.id}})});res.json({ok:true,reward:r.rewardTsx})});
app.get("/chat/:channel",async(req,res)=>res.json(await prisma.chatMessage.findMany({where:{channel:String(req.params.channel).slice(0,30)},orderBy:{id:"desc"},take:100,include:{user:{select:{username:true}}}})));
app.post("/chat/:channel",auth,async(req,res)=>{const u=req.user as Token,m=String(req.body.message||"").trim();if(!m||m.length>500)return res.status(400).json({error:"Mensaje inválido"});res.json(await prisma.chatMessage.create({data:{userId:u.id,channel:String(req.params.channel).slice(0,30),message:m},include:{user:{select:{username:true}}}}))});
app.get("/notifications",auth,async(req,res)=>res.json(await prisma.notification.findMany({where:{userId:(req.user as Token).id},orderBy:{id:"desc"},take:50})));
app.get("/admin/stats",auth,async(req,res)=>{const u=req.user as Token;if(![Role.ADMIN,Role.SUPER_ADMIN].includes(u.role))return res.status(403).json({error:"Solo admin"});const [users,planets,orders,battles]=await Promise.all([prisma.user.count(),prisma.planet.count(),prisma.marketOrder.count(),prisma.battleReport.count()]);res.json({users,planets,orders,battles})});
app.get("/v4/status",auth,async(_,res)=>res.json({version:"4.0.0",modules:["hangar","defense","advanced-battle","fleet-cargo","expedition-events","season-ranking","referrals","orderbook","web3-adapter-ready"]}));
wss.on("connection",ws=>ws.send(JSON.stringify({type:"connected",service:"trendshopx-gamefi",version:"4.0.0"})));
process.on("SIGINT",async()=>{await prisma.$disconnect();process.exit(0)});
http.listen(PORT,()=>console.log("TrendShopX GameFi API v4 listening on "+PORT));
