import express from "express";
import cors from "cors";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import dotenv from "dotenv";
import rateLimit from "express-rate-limit";
import {PrismaClient,Asset,LedgerType,Role,JobType,JobStatus,ResearchType,ShipType,DefenseType,FleetStatus,FleetMission,NotificationType,OrderSide,OrderStatus,BlockchainProvider} from "@prisma/client";
import {createServer} from "node:http";
import {WebSocketServer} from "ws";
dotenv.config();
const prisma=new PrismaClient(),app=express(),http=createServer(app),wss=new WebSocketServer({server:http,path:"/ws"});
const PORT=Number(process.env.API_PORT||4000),SECRET=process.env.JWT_SECRET||"dev-secret",FEE=Number(process.env.MARKET_FEE_PERCENT||3);
app.use(cors());app.use(express.json({limit:"200kb"}));app.use(rateLimit({windowMs:60000,max:Number(process.env.RATE_LIMIT||120)}));
type Token={id:number,username:string,role:Role};
const auth=(req:any,res:any,next:any)=>{const h=String(req.headers.authorization||"");if(!h.startsWith("Bearer "))return res.status(401).json({error:"No autenticado"});try{req.user=jwt.verify(h.slice(7),SECRET) as Token;next()}catch{return res.status(401).json({error:"Token inválido"})}};
const sign=(u:Token)=>jwt.sign(u,SECRET,{expiresIn:"7d"});
const n=(v:any,min=0)=>{const x=Number(v);return Number.isFinite(x)&&x>=min?x:null};
const ships:any={MINER:{a:4,d:12,s:80,c:[500,250,0]},FIGHTER:{a:20,d:10,s:180,c:[1000,500,100]},CRUISER:{a:45,d:30,s:140,c:[3000,1500,500]},TRANSPORT:{a:2,d:18,s:100,c:[2000,1000,100]},EXPLORER:{a:12,d:15,s:220,c:[1500,1200,400]},COLONY:{a:5,d:20,s:70,c:[10000,5000,1000]}};
const defenses:any={CANNON:[25,45,[500,100,0]],LASER:[40,25,[700,300,0]],PLASMA:[120,100,[5000,3000,500]],SHIELD:[5,500,[1000,1000,200]]};
async function tick(p:any){const now=new Date(),ms=Math.min(Math.max(0,now.getTime()-p.lastTick.getTime()),86400000),h=ms/36e5;if(ms<1000)return p;return prisma.planet.update({where:{id:p.id},data:{metal:{increment:30*p.metalMine*Math.pow(1.15,p.metalMine-1)*h},crystal:{increment:20*p.crystalMine*Math.pow(1.15,p.crystalMine-1)*h},deuterium:{increment:8*p.deutSynth*Math.pow(1.15,p.deutSynth-1)*h},lastTick:now}})}
async function finish(id:number){const jobs=await prisma.buildJob.findMany({where:{userId:id,status:JobStatus.QUEUED,finishAt:{lte:new Date()}},orderBy:{id:"asc"}});for(const j of jobs){if(j.type===JobType.BUILDING)await prisma.planet.update({where:{id:j.planetId},data:{[j.target]:{increment:1}}});if(j.type===JobType.RESEARCH){const r=await prisma.research.findUnique({where:{userId_type:{userId:id,type:j.target as ResearchType}}});if(r)await prisma.research.update({where:{id:r.id},data:{level:j.targetLevel}})}if(j.type===JobType.SHIP)await prisma.ship.upsert({where:{userId_type:{userId:id,type:j.target as ShipType}},update:{quantity:{increment:j.quantity}},create:{userId:id,type:j.target as ShipType,quantity:j.quantity}});if(j.type===JobType.DEFENSE)await prisma.defense.upsert({where:{planetId_type:{planetId:j.planetId,type:j.target as DefenseType}},update:{quantity:{increment:j.quantity}},create:{planetId:j.planetId,type:j.target as DefenseType,quantity:j.quantity}});await prisma.buildJob.update({where:{id:j.id},data:{status:JobStatus.DONE}})}}
async function notify(id:number,title:string,msg:string,type:NotificationType=NotificationType.SYSTEM){const x=await prisma.notification.create({data:{userId:id,title,message:msg,type}});const s=JSON.stringify({type:"notification",data:x});wss.clients.forEach(c=>{if(c.readyState===1)c.send(s)})}
async function activeSeason(){const now=new Date();return prisma.season.findFirst({where:{startsAt:{lte:now},endsAt:{gte:now}}})}
async function score(id:number,pts:number){const s=await activeSeason();if(s)await prisma.seasonScore.upsert({where:{seasonId_userId:{seasonId:s.id,userId:id}},update:{points:{increment:pts}},create:{seasonId:s.id,userId:id,points:pts}})}
app.get("/health",(_,r)=>r.json({ok:true,service:"trendshopx-gamefi",version:"5.0.0"}));
app.post("/auth/register",async(req,res)=>{const u=String(req.body.username||"").trim().toLowerCase(),p=String(req.body.password||"");if(!/^[a-z0-9_]{3,20}$/.test(u)||p.length<6)return res.status(400).json({error:"Usuario o contraseña inválidos"});try{const out=await prisma.$transaction(async tx=>{const used=await tx.planet.findMany({where:{galaxy:1,system:1},select:{position:true}}),set=new Set(used.map(x=>x.position));let pos=1;while(set.has(pos)&&pos<16)pos++;const user=await tx.user.create({data:{username:u,passwordHash:await bcrypt.hash(p,12)}}),planet=await tx.planet.create({data:{userId:user.id,name:"Capital",position:pos}});await tx.wallet.create({data:{userId:user.id,tsx:1000}});await tx.ledger.create({data:{userId:user.id,asset:Asset.TSX,amount:1000,type:LedgerType.BONUS,reference:"welcome"}});for(const t of Object.values(ResearchType))await tx.research.create({data:{userId:user.id,planetId:planet.id,type:t}});return {id:user.id,username:user.username,role:user.role}});res.json({token:sign(out as Token),user:out})}catch{return res.status(409).json({error:"Usuario ya existente o posición ocupada"})}});
app.post("/auth/login",async(req,res)=>{const u=await prisma.user.findUnique({where:{username:String(req.body.username||"").trim().toLowerCase()}});if(!u||!(await bcrypt.compare(String(req.body.password||""),u.passwordHash)))return res.status(401).json({error:"Credenciales incorrectas"});res.json({token:sign({id:u.id,username:u.username,role:u.role}),user:{id:u.id,username:u.username,role:u.role}})});
app.get("/me",auth,async(req,res)=>{const u=req.user as Token;await finish(u.id);const ps=await prisma.planet.findMany({where:{userId:u.id}});for(const p of ps)await tick(p);const fresh=await prisma.planet.findMany({where:{userId:u.id}}),wallet=await prisma.wallet.findUnique({where:{userId:u.id}}),shipsList=await prisma.ship.findMany({where:{userId:u.id}});res.json({user:u,planets:fresh,wallet,ships:shipsList,version:"5.0.0",marketFee:FEE})});
app.get("/planets",auth,async(req,res)=>{const ps=await prisma.planet.findMany({where:{userId:(req.user as Token).id}});for(const p of ps)await tick(p);res.json(await prisma.planet.findMany({where:{userId:(req.user as Token).id}}))});
app.post("/planets/colonize",auth,async(req,res)=>{const u=req.user as Token,pid=Number(req.body.planetId),p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}}),ship=await prisma.ship.findUnique({where:{userId_type:{userId:u.id,type:ShipType.COLONY}}});if(!p||!ship||ship.quantity<1)return res.status(400).json({error:"Necesitas una nave COLONY"});const g=Number(req.body.galaxy)||1,s=Number(req.body.system)||1,pos=Number(req.body.position)||Math.floor(Math.random()*15)+1;if(await prisma.planet.findUnique({where:{galaxy_system_position:{galaxy:g,system:s,position:pos}}}))return res.status(409).json({error:"Coordenadas ocupadas"});await prisma.ship.update({where:{userId_type:{userId:u.id,type:ShipType.COLONY}},data:{quantity:{decrement:1}}});res.json(await prisma.planet.create({data:{userId:u.id,name:String(req.body.name||"Colonia"),galaxy:g,system:s,position:pos}}))});
app.post("/build",auth,async(req,res)=>{const u=req.user as Token,pid=Number(req.body.planetId),target=String(req.body.target||""),p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}});const allowed=["metalMine","crystalMine","deutSynth","powerPlant","hangarLevel","defenseLevel","researchLab","shipyard"];if(!p||!allowed.includes(target))return res.status(400).json({error:"Edificio inválido"});await tick(p);const fresh=await prisma.planet.findUnique({where:{id:pid}}) as any,level=Number(fresh[target]),base=[150,100,0],cost={metal:Math.ceil(base[0]*Math.pow(1.55,level-1)),crystal:Math.ceil(base[1]*Math.pow(1.55,level-1)),deuterium:0};if(fresh.metal<cost.metal||fresh.crystal<cost.crystal)return res.status(400).json({error:"Recursos insuficientes",cost});await prisma.planet.update({where:{id:pid},data:{metal:{decrement:cost.metal},crystal:{decrement:cost.crystal}}});res.json(await prisma.buildJob.create({data:{userId:u.id,planetId:pid,type:JobType.BUILDING,target,targetLevel:level+1,finishAt:new Date(Date.now()+Math.max(1,level)*60000)}}))});
app.get("/jobs",auth,async(req,res)=>{const u=req.user as Token;await finish(u.id);res.json(await prisma.buildJob.findMany({where:{userId:u.id},orderBy:{id:"desc"},take:100}) )});
app.get("/research",auth,async(req,res)=>res.json(await prisma.research.findMany({where:{userId:(req.user as Token).id}})));
app.post("/research/upgrade",auth,async(req,res)=>{const u=req.user as Token,t=String(req.body.type||"") as ResearchType,pid=Number(req.body.planetId),r=await prisma.research.findUnique({where:{userId_type:{userId:u.id,type:t}}}),p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}});if(!r||!p)return res.status(404).json({error:"Investigación no encontrada"});const cost={metal:Math.ceil(800*Math.pow(1.7,r.level-1)),crystal:Math.ceil(500*Math.pow(1.7,r.level-1)),deuterium:Math.ceil(200*Math.pow(1.7,r.level-1))};if(p.metal<cost.metal||p.crystal<cost.crystal||p.deuterium<cost.deuterium)return res.status(400).json({error:"Recursos insuficientes",cost});await prisma.planet.update({where:{id:pid},data:{metal:{decrement:cost.metal},crystal:{decrement:cost.crystal},deuterium:{decrement:cost.deuterium}}});res.json(await prisma.buildJob.create({data:{userId:u.id,planetId:pid,type:JobType.RESEARCH,target:t,targetLevel:r.level+1,finishAt:new Date(Date.now()+Math.max(2,r.level)*120000)}}))});
app.get("/ships",auth,async(req,res)=>res.json(await prisma.ship.findMany({where:{userId:(req.user as Token).id}})));
app.post("/ships/build",auth,async(req,res)=>{const u=req.user as Token,t=String(req.body.type||"") as ShipType,q=n(req.body.quantity,1),pid=Number(req.body.planetId);if(!q||!ships[t])return res.status(400).json({error:"Nave inválida"});const p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}}),c=ships[t].c;if(!p)return res.status(404).json({error:"Planeta"});const total={metal:c[0]*q,crystal:c[1]*q,deuterium:c[2]*q};if(p.metal<total.metal||p.crystal<total.crystal||p.deuterium<total.deuterium)return res.status(400).json({error:"Recursos insuficientes",cost:total});await prisma.planet.update({where:{id:pid},data:{metal:{decrement:total.metal},crystal:{decrement:total.crystal},deuterium:{decrement:total.deuterium}}});res.json(await prisma.buildJob.create({data:{userId:u.id,planetId:pid,type:JobType.SHIP,target:t,targetLevel:1,quantity:q,finishAt:new Date(Date.now()+Math.ceil(q/2)*60000)}}))});
app.get("/defenses",auth,async(req,res)=>{const p=await prisma.planet.findFirst({where:{id:Number(req.query.planetId),userId:(req.user as Token).id}});if(!p)return res.status(404).json({error:"Planeta"});res.json(await prisma.defense.findMany({where:{planetId:p.id}}))});
app.post("/defenses/build",auth,async(req,res)=>{const u=req.user as Token,t=String(req.body.type||"") as DefenseType,q=n(req.body.quantity,1),pid=Number(req.body.planetId);const p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}}),d=defenses[t];if(!p||!q||!d)return res.status(400).json({error:"Defensa inválida"});const c={metal:d[2][0]*q,crystal:d[2][1]*q,deuterium:d[2][2]*q};if(p.metal<c.metal||p.crystal<c.crystal||p.deuterium<c.deuterium)return res.status(400).json({error:"Recursos insuficientes",cost:c});await prisma.planet.update({where:{id:pid},data:{metal:{decrement:c.metal},crystal:{decrement:c.crystal},deuterium:{decrement:c.deuterium}}});res.json(await prisma.buildJob.create({data:{userId:u.id,planetId:pid,type:JobType.DEFENSE,target:t,targetLevel:1,quantity:q,finishAt:new Date(Date.now()+Math.ceil(q/5)*60000)}}))});
app.get("/fleets",auth,async(req,res)=>res.json(await prisma.fleet.findMany({where:{userId:(req.user as Token).id},include:{origin:true,destination:true}})));
app.post("/fleets",auth,async(req,res)=>{const u=req.user as Token,pid=Number(req.body.planetId),p=await prisma.planet.findFirst({where:{id:pid,userId:u.id}});if(!p)return res.status(404).json({error:"Planeta"});res.json(await prisma.fleet.create({data:{userId:u.id,planetId:pid,name:String(req.body.name||"Fleet"),ships:req.body.ships||{},attack:10,defense:10}}))});
app.post("/fleets/dispatch",auth,async(req,res)=>{const u=req.user as Token,f=await prisma.fleet.findFirst({where:{id:Number(req.body.fleetId),userId:u.id,status:FleetStatus.IDLE}}),d=await prisma.planet.findUnique({where:{id:Number(req.body.destinationPlanetId)}});if(!f||!d||d.id===f.planetId)return res.status(400).json({error:"Flota/destino inválido"});const arr=new Date(Date.now()+Math.max(1,Number(req.body.minutes)||5)*60000);res.json(await prisma.fleet.update({where:{id:f.id},data:{status:FleetStatus.TRAVELING,mission:String(req.body.mission||"TRANSPORT") as FleetMission,destinationPlanetId:d.id,departureAt:new Date(),arrivalAt:arr,cargo:req.body.cargo||{}}}))});
app.post("/fleets/arrive",auth,async(req,res)=>{const u=req.user as Token,f=await prisma.fleet.findFirst({where:{id:Number(req.body.fleetId),userId:u.id,status:FleetStatus.TRAVELING}});if(!f||!f.arrivalAt||f.arrivalAt>new Date())return res.status(400).json({error:"Flota aún en viaje"});res.json(await prisma.fleet.update({where:{id:f.id},data:{status:FleetStatus.RETURNING}}))});
app.post("/battle/:defenderId",auth,async(req,res)=>{const u=req.user as Token,did=Number(req.params.defenderId);if(did===u.id)return res.status(400).json({error:"Objetivo inválido"});const a=await prisma.user.findUnique({where:{id:u.id},include:{ships:true}}),d=await prisma.user.findUnique({where:{id:did},include:{ships:true,defenses:true,planets:true}});if(!a||!d)return res.status(404).json({error:"Jugador"});const ap=a.ships.reduce((s,x)=>s+x.quantity*(ships[x.type]?.a||0),0),dp=d.ships.reduce((s,x)=>s+x.quantity*(ships[x.type]?.a||0),0)+d.defenses.reduce((s,x)=>s+x.quantity*x.attack,0);const aw=Math.max(0,Math.floor(ap*(0.65+Math.random()*.35))),dw=Math.max(0,Math.floor(dp*(0.65+Math.random()*.35))),winner=aw>=dw?u.id:did;const al=a.ships.map(x=>({type:x.type,lost:Math.min(x.quantity,Math.floor(x.quantity*(dw/(ap+1)*.25)))})),dl=d.ships.map(x=>({type:x.type,lost:Math.min(x.quantity,Math.floor(x.quantity*(aw/(dp+1)*.25)))}));for(const x of al)if(x.lost)await prisma.ship.update({where:{userId_type:{userId:u.id,type:x.type}},data:{quantity:{decrement:x.lost}}});for(const x of dl)if(x.lost)await prisma.ship.update({where:{userId_type:{userId:did,type:x.type}},data:{quantity:{decrement:x.lost}}});const report=await prisma.battleReport.create({data:{attackerId:u.id,defenderId:did,winnerId:winner,attackerPower:aw,defenderPower:dw,attackerLosses:al,defenderLosses:dl,loot:{metal:winner===u.id?Math.floor((d.planets[0]?.metal||0)*.1):0}}});await score(winner,25);await notify(did,"Batalla","Has recibido un reporte de batalla",NotificationType.BATTLE);res.json(report)});
app.get("/ranking",auth,async(_,res)=>{const s=await activeSeason();if(s){const rows=await prisma.seasonScore.findMany({where:{seasonId:s.id},include:{user:{select:{username:true}}},orderBy:{points:"desc"},take:100});return res.json(rows)}const rows=await prisma.user.findMany({select:{id:true,username:true,wallet:{select:{tsx:true}}},orderBy:{id:"asc"},take:100});res.json(rows)});
app.get("/seasons",async(_,res)=>res.json(await prisma.season.findMany({include:{scores:{include:{user:{select:{username:true}}},orderBy:{points:"desc"},take:100}},orderBy:{startsAt:"desc"}})));
app.post("/admin/seasons",auth,async(req,res)=>{const u=req.user as Token;if(![Role.ADMIN,Role.SUPER_ADMIN].includes(u.role))return res.status(403).json({error:"Solo admin"});res.json(await prisma.season.create({data:{name:String(req.body.name||"Temporada"),startsAt:new Date(req.body.startsAt),endsAt:new Date(req.body.endsAt)}}))});
app.get("/referrals",auth,async(req,res)=>{const u=req.user as Token;const me=await prisma.user.findUnique({where:{id:u.id},select:{referralCode:true}});res.json({code:me?.referralCode,items:await prisma.referral.findMany({where:{OR:[{referrerId:u.id},{referredId:u.id}]}})})});
app.post("/referrals/activate",auth,async(req,res)=>{const u=req.user as Token,r=await prisma.referral.findUnique({where:{referredId:u.id}});if(!r||r.status!=="PENDING")return res.status(400).json({error:"No hay referido pendiente"});await prisma.$transaction([prisma.referral.update({where:{id:r.id},data:{status:"REWARDED",rewardedAt:new Date()}}),prisma.wallet.update({where:{userId:r.referrerId},data:{tsx:{increment:r.rewardTsx}}}),prisma.ledger.create({data:{userId:r.referrerId,asset:Asset.TSX,amount:r.rewardTsx,type:LedgerType.REWARD,reference:"referral:"+r.id}})]);res.json({ok:true,reward:r.rewardTsx})});
app.post("/spy/:planetId",auth,async(req,res)=>{const u=req.user as Token,target=await prisma.planet.findUnique({where:{id:Number(req.params.planetId)},include:{user:true,defenses:true}});if(!target||target.userId===u.id)return res.status(400).json({error:"Objetivo inválido"});const intel={planet:target.name,metal:Math.floor(target.metal),crystal:Math.floor(target.crystal),deuterium:Math.floor(target.deuterium),defenses:target.defenses.map(x=>({type:x.type,quantity:x.quantity}))};const report=await prisma.spyReport.create({data:{senderId:u.id,targetId:target.userId,targetPlanetId:target.id,status:"COMPLETED",intel}});await score(u.id,5);res.json(report)});
app.get("/spy/reports",auth,async(req,res)=>res.json(await prisma.spyReport.findMany({where:{senderId:(req.user as Token).id},orderBy:{id:"desc"},take:50})));
app.get("/missions/daily",auth,async(req,res)=>res.json([{code:"BUILD",title:"Constructor",description:"Mejora un edificio",rewardTsx:50},{code:"EXPLORE",title:"Explorador",description:"Completa una expedición",rewardTsx:75},{code:"BATTLE",title:"Comandante",description:"Participa en una batalla",rewardTsx:100}]));
app.get("/market",auth,async(_,res)=>res.json(await prisma.marketOrder.findMany({where:{status:OrderStatus.OPEN},include:{user:{select:{username:true}}},orderBy:{price:"asc"},take:100})));
app.get("/wallet/ledger",auth,async(req,res)=>res.json(await prisma.ledger.findMany({where:{userId:(req.user as Token).id},orderBy:{id:"desc"},take:100})));
app.post("/web3/simulate/deposit",auth,async(req,res)=>{const u=req.user as Token,a=String(req.body.asset||"USDT") as Asset,amount=n(req.body.amount,.0001);if(!amount||!Object.values(Asset).includes(a))return res.status(400).json({error:"Depósito inválido"});const tx="sim_"+Date.now();await prisma.wallet.update({where:{userId:u.id},data:{[a.toLowerCase()]:{increment:amount}}});await prisma.chainTransaction.create({data:{userId:u.id,provider:BlockchainProvider.SIMULATED_EVM,asset:a,direction:"DEPOSIT",txHash:tx,amount}});res.json({mode:"SIMULATED",txHash:tx,amount,asset:a})});
app.get("/admin/stats",auth,async(req,res)=>{const u=req.user as Token;if(![Role.ADMIN,Role.SUPER_ADMIN].includes(u.role))return res.status(403).json({error:"Solo admin"});const [users,planets,fleets,battles,spies]=await Promise.all([prisma.user.count(),prisma.planet.count(),prisma.fleet.count(),prisma.battleReport.count(),prisma.spyReport.count()]);res.json({users,planets,fleets,battles,spies})});
app.get("/v5/status",auth,(_,res)=>res.json({version:"5.0.0",modules:["multi-planet","tech-tree","hangar","defense","fleet-lifecycle","combat-round","espionage","colonization","daily-missions","season-ranking","referrals","p2p-orderbook","admin"]}));
wss.on("connection",ws=>ws.send(JSON.stringify({type:"connected",version:"5.0.0"})));
http.listen(PORT,()=>console.log("TrendShopX GameFi API V5 on "+PORT));
